### ISSUE TITLE
An error occurred while running the code

### ISSUE THREAD

**Issue by jamerri** [SunzidHassan/24_Vision-Olfaction-LLM#2]
I tried to run the code you provided, but the following error occurred. I tried for a long time but still couldn't solve the problem.The error message is as follows:
“Traceback (most recent call last):
  File "C:\Project_code\PycharmProjects\24_LLM-OSL-main\LLM_demo.py", line 41, in <module>
    response = payload(api_key, prompt, image_base64, gpt_model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project_code\PycharmProjects\24_LLM-OSL-main\gptPayload.py", line 31, in payload
    response = requests.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload).json()['choices'][0]['message']['content']
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'choices'”

**Comment by SunzidHassan** [comment]
can you change the line to:
```
response = requests.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload).json()
```
and let me know the output?

**Comment by jamerri** [comment]
The output is as follows:
"Please enter a timestamp (1-12): 2
Chemical concentration: 482
{'error': {'message': 'The model `gpt-4o` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
"

**Comment by SunzidHassan** [comment]
Have you configured the openai api?

**Comment by jamerri** [comment]
Yes, I have configured the API, but I am not sure which model my API uses. Do you have any good suggestions?

**Comment by SunzidHassan** [comment]
You can try running 'gpt-4o-mini'. You need to select a model that supports image input ('gpt-3.5-turbo' doesn't support image input). You can find more models in this link: https://platform.openai.com/docs/models

**Comment by jamerri** [comment]
Thanks for your reply, I'll try again.

**Comment by dongdong-W** [comment]
Hello, I'm a beginner. I have a bit of confusion and hope you can help me figure it out. In the open-source code you provided, does it only offer visual and olfactory data for large model processing without providing algorithms related to YOLO to detect steam in pictures? Is that the case? I'm looking forward to your answer. Wish you a happy day every day.
